apiVersion: v1
kind: Service
metadata:
  name: {{ template "feast.serving.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "feast.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
  - name: grpc
    port: {{ .Values.serving.service.grpc.port }}
    targetPort: {{ .Values.serving.service.grpc.targetPort }}
  - name: http
    port: {{ .Values.serving.service.http.port }}
    targetPort: {{ .Values.serving.service.http.targetPort }}
  selector:
    app: {{ template "feast.name" . }}
    component: serving
    release: {{ .Release.Name }}
