# This patch adds v1alpha1 as a deprecated version to support migration from previous versions
# v1alpha1 is marked as served: true and storage: false to allow v1alpha1 resources to be created
# and served, but they are stored as v1 internally. This supports upgrade testing and migration.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: featurestores.feast.dev
spec:
  group: feast.dev
  names:
    kind: FeatureStore
    listKind: FeatureStoreList
    plural: featurestores
    shortNames:
    - feast
    singular: featurestore
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          description: FeatureStore is the Schema for the featurestores API (deprecated, use v1 instead)
          properties:
            apiVersion:
              description: APIVersion defines the versioned schema of this representation of an object.
              type: string
            kind:
              description: Kind is a string value representing the REST resource this object represents.
              type: string
            metadata:
              type: object
            spec:
              description: FeatureStoreSpec defines the desired state of FeatureStore
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              description: FeatureStoreStatus defines the observed state of FeatureStore
              type: object
              x-kubernetes-preserve-unknown-fields: true
          type: object
      subresources:
        status: {}

