apiVersion: v1
description: "Feast Feature Server: Online feature serving service for Feast"
name: feature-server
version: 0.20.1
appVersion: v0.20.1
keywords:
- machine learning
- big data
- mlops
home: https://github.com/feast-dev/feast