feast:
  core-host: core
  active-store: historical
  stores:
    - name: historical
      type: BIGQUERY
      # Changes required for batch serving to work
      # Please see https://api.docs.feast.dev/grpc/feast.core.pb.html#Store for configuration options
      config:
        project_id: project
        dataset_id: dataset
        staging_location: gs://gcs_bucket/prefix
        initial_retry_delay_seconds: 1
        total_timeout_seconds: 21600
        write_triggering_frequency_seconds: 600
      subscriptions:
        - name: "*"
          project: "*"
  job_store:
    redis_host: redis
    redis_port: 6379
  
grpc:
  port: 6567
