presubmits:
  gojek/feast:
  - name: presubmit-unit-tests
    always_run: true
    spec:
      containers:
      - image: us.gcr.io/kf-feast/test-image:1.0.0
        args: ["make", "test"]
        imagePullPolicy: Always
  - name: presubmit-integration-test-batch
    always_run: false
    spec:
      containers:
      - image: us.gcr.io/kf-feast/test-image:1.0.0
        args: ["make", "test-integration", "ID=$PULL_NUMBER", "TYPE=PR"]
        imagePullPolicy: Always
    trigger: integration-batch
postsubmits:
  gojek/feast:
  - name: postsubmit-unit-tests
    always_run: true
    spec:
      containers:
      - image: us.gcr.io/kf-feast/test-image:1.0.0
        args: ["make", "test"]
        imagePullPolicy: Always
  - name: postsubmit-integration-test-batch
    always_run: true
    spec:
      containers:
      - image: us.gcr.io/kf-feast/test-image:1.0.0
        args: ["make", "test-integration", "ID=$PULL_BASE_REF", "TYPE=GITREF"]
        imagePullPolicy: Always
    trigger: integration-batch
tide:
  queries:
  - repos:
    - gojek/feast
    labels:
    - lgtm
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - needs-rebase
  merge_method:
    gojek/feast: squash
  blocker_label: merge-blocker
  squash_label: tide/squash