version: "3.7"

services:
  core:
    image: gcr.io/kf-feast/feast-core:${FEAST_VERSION}
    volumes:
      - ${FEAST_CORE_CONFIG}:/etc/feast/application.yml
      - ${GCP_SERVICE_ACCOUNT}:/etc/gcloud/service-accounts/key.json
    environment:
      DB_HOST: db
      GOOGLE_APPLICATION_CREDENTIALS: /etc/gcloud/service-accounts/key.json
    restart: on-failure
    depends_on:
      - db
      - kafka
    ports:
      - 6565:6565
    command:
      - java
      - -jar
      - /opt/feast/feast-core.jar
      - --spring.config.location=classpath:/application.yml,file:/etc/feast/application.yml

  jobcontroller:
    image: gcr.io/kf-feast/feast-jobcontroller:${FEAST_VERSION}
    volumes:
      - ${FEAST_jobcontroller_CONFIG}:/etc/feast/application.yml
      - ${GCP_SERVICE_ACCOUNT}:/etc/gcloud/service-accounts/key.json
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /etc/gcloud/service-accounts/key.json
    depends_on:
      - kafka
    ports:
      - 6570:6570
    command:
      - java
      - -jar
      - /opt/feast/feast-job-controller.jar
      - --spring.config.location=classpath:/application.yml,file:/etc/feast/application.yml

  jupyter:
    image: gcr.io/kf-feast/feast-jupyter:${FEAST_VERSION}
    volumes:
      - ${GCP_SERVICE_ACCOUNT}:/etc/gcloud/service-accounts/key.json
    depends_on:
      - core
    environment:
      FEAST_CORE_URL: core:6565
      FEAST_ONLINE_SERVING_URL: online_serving:6566
      FEAST_HISTORICAL_SERVING_URL: historical_serving:6567
      GOOGLE_APPLICATION_CREDENTIALS: /etc/gcloud/service-accounts/key.json
    ports:
      - 8888:8888

  kafka:
    image: confluentinc/cp-kafka:5.2.1
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    ports:
      - "9092:9092"
      - "9094:9094"

    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  online_serving:
    image: gcr.io/kf-feast/feast-serving:${FEAST_VERSION}
    volumes:
      - ${FEAST_ONLINE_SERVING_CONFIG}:/etc/feast/application.yml
    depends_on:
      - redis
    ports:
      - 6566:6566
    restart: on-failure
    command:
      - java
      - -jar
      - /opt/feast/feast-serving.jar
      - --spring.config.location=classpath:/application.yml,file:/etc/feast/application.yml

  historical_serving:
    image: gcr.io/kf-feast/feast-serving:${FEAST_VERSION}
    volumes:
      - ${FEAST_HISTORICAL_SERVING_CONFIG}:/etc/feast/application.yml
      - ${GCP_SERVICE_ACCOUNT}:/etc/gcloud/service-accounts/key.json
    depends_on:
      - redis
    ports:
      - 6567:6567
    restart: on-failure
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /etc/gcloud/service-accounts/key.json
    command: >
      bash -c "if [ $FEAST_HISTORICAL_SERVING_ENABLED != "true" ]; then echo \"Feast historical serving is disabled\"; sleep 10; exit 1; fi
      && java -Xms1024m -Xmx1024m -jar /opt/feast/feast-serving.jar --spring.config.location=classpath:/application.yml,file:/etc/feast/application.yml"

  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"