version: "3.7"

services:
  online-serving:
    build:
      context: ../..
      dockerfile: infra/docker/serving/Dockerfile
    image: ${FEAST_SERVING_IMAGE}:${FEAST_VERSION}
    volumes:
      - ./serving/${FEAST_ONLINE_SERVING_CONFIG}:/etc/feast/application.yml
    depends_on:
      - redis
    ports:
      - 6566:6566
    restart: on-failure
    environment:
      REDIS_PASS: ${REDIS_PASS}
      REDIS_HOST: ${REDIS_HOST}
    command:
      - java
      - -jar
      - /opt/feast/feast-serving.jar
      - --spring.config.location=classpath:/application.yml,file:/etc/feast/application.yml

  redis:
    image: redis:5-alpine
    command: redis-server --requirepass '${REDIS_PASS}'
    ports:
      - "6379:6379"
