apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "feast-serving.fullname" . }}-store-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "feast-serving.name" . }}
    component: serving
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  store.yaml: |
{{ toYaml .Values.store.config | indent 4 }}