[project]
name = "pixi-feast"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64"]

[tasks]

[dependencies]
uv = ">=0.6.3"

[feature.py39.dependencies]
python = "~=3.9.0"

[feature.py310.dependencies]
python = "~=3.10.0"

[feature.py311.dependencies]
python = "~=3.11.0"

[environments]
py39 = ["py39"]
py310 = ["py310"]
py311 = ["py311"]
