apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "prometheus-statsd-exporter.fullname" . }}
  labels:
    app: {{ template "prometheus-statsd-exporter.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.statsdexporter.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "prometheus-statsd-exporter.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
{{ toYaml .Values.statsdexporter.podAnnotations | indent 8 }}
      labels:
        app: {{ template "prometheus-statsd-exporter.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "prometheus-statsd-exporter.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --statsd.mapping-config=/etc/statsd_conf/statsd_mappings.yaml
          {{- range $key, $value := .Values.statsdexporter.extraArgs }}
            - --{{ $key }}={{ $value }}
          {{- end }}
          volumeMounts:
          - mountPath: /data
            name: {{ .Values.persistentVolume.name }}
          - name: statsd-config
            mountPath: /etc/statsd_conf
          env:
          - name: HOME
            value: /data
          ports:
            - name: metrics
              containerPort: 9102
              protocol: TCP
            - name: statsd-tcp
              containerPort: 9125
              protocol: TCP
            - name: statsd-udp
              containerPort: 9125
              protocol: UDP
          livenessProbe:
            httpGet:
              path: /#/status
              port: 9102
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /#/status
              port: 9102
            initialDelaySeconds: 10
            timeoutSeconds: 10
          resources:
{{ toYaml .Values.statsdexporter.resources | indent 12 }}
{{- if .Values.statsdexporter.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.statsdexporter.nodeSelector | indent 8 }}
    {{- end }}
      volumes:
      - name: statsd-config
        configMap:
          name: {{ template "prometheus-statsd-exporter.fullname" . }}-config
      - name: {{ .Values.persistentVolume.name }}
        {{- if .Values.persistentVolume.enabled }}
        persistentVolumeClaim:
        claimName: {{ if .Values.persistentVolume.claimName }}{{- else }}{{ template "prometheus-statsd-exporter.fullname" . }}{{- end }}
        {{- else }}
        emptyDir: {}
        {{- end -}}
