apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "feast-jc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "feast-jc.name" . }}
    component: jc
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application-generated.yaml: |
{{- if index .Values "application-generated.yaml" "enabled" }}
    feast:
      core-host: {{ .Release.Name }}-feast-core
      stream:
        type: kafka
        options: 
          bootstrapServers: {{ .Release.Name }}-kafka:9092
          topic: feast
      jobs:
        metrics:
          enabled: true 
          type: statsd
          host: {{ .Release.Name }}-prometheus-statsd-exporter-udp
          port: 9125

    server:
      port: {{ .Values.service.http.targetPort }}
{{- end }}

  application-override.yaml: |
{{- if index .Values "application-override.yaml" "enabled" }}
{{- toYaml (index .Values "application-override.yaml") | nindent 4 }}    
{{- end }}