apiVersion: v1
description: "Transformation service: to compute on-demand features"
name: transformation-service
version: 0.23.1
appVersion: v0.23.1
keywords:
- machine learning
- big data
- mlops
home: https://github.com/feast-dev/feast