apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: feast
  name: otel-sm
spec:
  endpoints:
    - port: metrics
  namespaceSelector:
    matchNames:
      - <namespace> # helm value - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/component: opentelemetry-collector
      app.kubernetes.io/managed-by: opentelemetry-operator    