name: operator-pr

on: [pull_request]
jobs:
  operator-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x
      - name: Operator tests
        run: |
          cd infra/feast-operator/
          make test
      - name: After code formatting, check for uncommitted differences
        run: git diff --exit-code infra/feast-operator
